/*
 * This ratpack file was auto generated by 'gigawatt'
 * @author d7392
 * @date 16-06-2018 02.36
 */
// external
import static ratpack.groovy.Groovy.ratpack
// internal

ratpack {
	handlers {
		get {
			render 'This application was auto generated by "gigawatt"'
		}
	}
}
