
/*
 * This ratpack file was auto generated by 'gigawatt'
 * @author gsus
 * @date 21-06-2017 14.14
 *
 * Example conf class
 * ------------------
 * class YextApi {
 *   String key
 *   String url
 * }
 *
 * Corresponding env variables
 * ---------------------------
 * export RATPACK_YEXT__API__KEY='123abcd'
 * export RATPACK_YEXT__API__URL='https://api.yext.com/v2'
 */
// external
import static ratpack.groovy.Groovy.ratpack
import ratpack.hikari.HikariModule
import com.zaxxer.hikari.HikariConfig
import ratpack.groovy.sql.SqlModule
import ratpack.groovy.template.MarkupTemplateModule
import static ratpack.groovy.Groovy.groovyMarkupTemplate
// internal

ratpack {
	bindings {
		module(MarkupTemplateModule) { c ->
			c.autoNewLine = true
			c.autoIndent  = true
		}
		Properties hikariConfigProperties = serverConfig.get("/iolconnect/db", Properties)
		moduleConfig(
			HikariModule,
			new HikariConfig(hikariConfigProperties)
		)
		module(SqlModule)
	}
}
